# Sends an automated notification containing who pushed, what repo, the commit message, and a direct link to view the commit
# to a Discord channel when a new commit is pushed to the main branch of the repository. 
name: Custom Discord Notification

on:
    push:
        branches: [main]

jobs:
    notify:
        runs-on: ubuntu-latest

        steps:
           - name: Send Custom Discord Notification
             uses: Ilshidur/action-discord@master
             env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
             with:
                args: |
                  **New Commit Pushed**
                  **Repository:** ${{ github.repository }}
                  **Committer:** ${{ github.actor }}
                  **Commit Message:** ${{ github.event.head_commit.message }}
                  **Go To Commit:** [Link](${{ github.event.head_commit.url }})
